POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Uusi blogi Hannun uudella tokenilla!!!",
    "author": "Minää",
    "url": "http://www.omablogi.fi/2024_08_lkjkln",
    "likes": 0
}