POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Ankkalinnan kuulumisia",
    "author": "Iines",
    "url": "http://www.omablogi.fi/2024_08_lkjohn",
    "likes": 0,
    "userId": "663472eea4be81e0a4d84386"
}