POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCIpIkpXVCJ9.eyJ1c2VybmFtZSI6Imhhbm51aGFuaGkiLCJpZCI6IjY2MzQ3MmVlYTRiZTgxZTBhNGQ4NDM4NiIsImlhdCI6MTcxNDcxODYzOH0.N0tCrjF_duJTrJ0blkAjKC_mjxTI6bytv-dRsD6xuOA

{
    "title": "Uusi blogi Hannun uudella tokenilla!!!",
    "author": "Minää",
    "url": "http://www.omablogi.fi/2024_08_lkjkln",
    "likes": 0
}